config/routes.rb
Bdt270::Application.routes.draw do
resources :inquiries, :only => [:index, :show, :new, :create] do  
  collection do
  get 'capture'
  post 'save_image'
  post 'upload'
end  
end

  root 'inquiries#new'

end

app/models/inquiry.rb
class Inquiry < Activerecord::Base
	validates :nom, presence: true
	validates :prénom, presence: true
	validates :téléphone, presence: true
	validates :voie, presence: true
	validates :message, presence: true
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/appartements_controller.rb
class AppartementsController < ApplicationController
	def index
		voie = params[:voie]
		if voie == 'Francis Garnier'
			@numeros = [1,2,3,4,6,8]
		elsif voie == 'Pérouse'
			@numeros = [2,4,6]
		elsif voie == 'Bougainville'
			@numeros = [1,2,3,4,5,6,7,8,9,10,11,12,13]
		elsif voie == 'Jacques Cartier'
			@numeros = [1,2]
     	elsif voie == 'Champlain'
     		@numeros = [1,3,5,7]
     	end
			
		render inline: '<%= select_tag "numero", options_for_select(@numeros) %>'
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exterieurs1_controller.rb
class Exterieurs1Controller < ApplicationController
	def index
		voie3 = params[:voie3]
		if voie3 == 'Francis Garnier'
			@numeros = [1,2,3,4,6,8]
		elsif voie3 == 'Pérouse'
			@numeros = [2,4,6]
		elsif voie3 == 'Bougainville'
			@numeros = [1,2,3,4,5,6,7,8,9,10,11,12,13]
		elsif voie3 == 'Jacques Cartier'
			@numeros = [1,2]
     	elsif voie3 == 'Champlain'
     		@numeros = [1,3,5,7]
     	end
			
		render inline: '<%= select_tag "numero", options_for_select(@numeros) %>'
	end
end

app/controllers/exterieurs2_controller.rb
class Exterieurs2Controller < ApplicationController
	def index
		voie4 = params[:voie4]
		if voie4 == 'Francis Garnier'
			@numeros = [1,2,3,4,6,8]
		elsif voie4 == 'Pérouse'
			@numeros = [2,4,6]
		elsif voie4 == 'Bougainville'
			@numeros = [1,2,3,4,5,6,7,8,9,10,11,12,13]
		elsif voie4 == 'Jacques Cartier'
			@numeros = [1,2]
     	elsif voie4 == 'Champlain'
     		@numeros = [1,3,5,7]
     	end
			
		render inline: '<%= select_tag "numero", options_for_select(@numeros) %>'
	end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def create
    @inquiry = Inquiry.new(params[:inquiry])
    @inquiry.image = File.new(upload_path)
    @inquiry.save

    redirect_to @inquiry
  end

  def show
    @inquiry = Inquiry.find(params[:id])
  end

  def index
    @inquiries = Inquiry.all
  end

  def upload
    File.open(upload_path, 'wb') do |f|
      f.write request.raw_post
    end
    render :text => "ok"
  end

  private

  def upload_path # is used in upload and create
    File.join(Rails.root, 'tmp', 'photo.jpg')
  end
end

app/controllers/interieurs1_controller.rb
class Interieurs1Controller < ApplicationController
	def index
		voie1 = params[:voie1]
		if voie1 == 'Francis Garnier'
			@numeros = [1,2,3,4,6,8]
		elsif voie1 == 'Pérouse'
			@numeros = [2,4,6]
		elsif voie1 == 'Bougainville'
			@numeros = [1,2,3,4,5,6,7,8,9,10,11,12,13]
		elsif voie1 == 'Jacques Cartier'
			@numeros = [1,2]
     	elsif voie1 == 'Champlain'
     		@numeros = [1,3,5,7]
     	end
			
		render inline: '<%= select_tag "numero", options_for_select(@numeros) %>'
	end
end

app/controllers/interieurs2_controller.rb
class Interieurs2Controller < ApplicationController
	def index
		voie2 = params[:voie2]
		if voie2 == 'Francis Garnier'
			@numeros = [1,2,3,4,6,8]
		elsif voie2 == 'Pérouse'
			@numeros = [2,4,6]
		elsif voie2 == 'Bougainville'
			@numeros = [1,2,3,4,5,6,7,8,9,10,11,12,13]
		elsif voie2 == 'Jacques Cartier'
			@numeros = [1,2]
     	elsif voie2 == 'Champlain'
     		@numeros = [1,3,5,7]
     	end
			
		render inline: '<%= select_tag "numero", options_for_select(@numeros) %>'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/exterieurs1_helper.rb
module Exterieurs1Helper
end

app/helpers/exterieurs2_helper.rb
module Exterieurs2Helper
end

app/helpers/interieurs1_helper.rb
module Interieurs1Helper
end

app/helpers/interieurs2_helper.rb
module Interieurs2Helper
end

app/views/exterieurs1/index.html.erb
<h1>Exterieurs1#index</h1>
<p>Find me in app/views/exterieurs1/index.html.erb</p>

app/views/exterieurs2/index.html.erb
<h1>Exterieurs2#index</h1>
<p>Find me in app/views/exterieurs2/index.html.erb</p>

app/views/inquiries/create.html.erb
<h1>Message#create</h1>
<p>Find me in app/views/message/create.html.erb</p>

app/views/inquiries/index.html.erb
<h1>All photos</h1>
<p>
  <% @inquiries.each do |inquiry| %>
    <%= link_to image_tag(inquiry.image.url(:thumb)), inquiry %>
  <% end %>
</p>
<p>
  <%= link_to "Take a new picture", new_inquiry_path %>
</p>

app/views/inquiries/new.html.erb
<div class="container text-center">
	<div class="menu1">
		<button type="button" class="btn btn-default">Mon appartement</button></br>
		<div class="questionnaire1 text-center">
			<form action=''>
				<input type="texte" value="nom"> </br>
				<input type="text" value="prénom"> </br>
				<input type="texte" value="Téléphone"> </br>
				<select id="voie" class="form-control">
					<option>Voie</option>
					<option>Francis Garnier</option>
					<option>Pérouse</option>
					<option>Bougainville</option>
					<option>Jacques Cartier</option>
					<option>Champlain</option>
				</select>
				<div class="text-center">
					<textarea class="form-control" rows="4"></textarea>
					<input type="submit" value="Envoyer">
				</div>
			</form>
			<%= render "layouts/webcam" %>
		</div>
	</div>

	<div class="menu2">
		<button type="button" class="btn btn-default">Espaces intérieurs</button>
	</div>

	<div class="row">
		<div class="questionnaire2 text-center">
			<button type="button" class="btn btn-default hall1"> Hall d'entrée </button> <button type="button" class="btn btn-default hall2"> Hall à l'étage</button>
		</div>
		<div id="hall1-bis">
			<form action=''>
				<input type="texte" value="nom"> </br>
				<input type="text" value="prénom"> </br>
				<input type="texte" value="Téléphone"> </br>
				<select id="voie1" class="form-control">
					<option>voie</option>
					<option>Francis Garnier</option>
					<option>Pérouse</option>
					<option>Bougainville</option>
					<option>Jacques Cartier</option>
					<option>Champlain</option>					
				</select>
				<div class="text-center">
					<textarea class="form-control" rows="3"></textarea>
					<input type="submit" value="Envoyer">
				</div>
			</form>
			<%= render "layouts/webcam" %>
		</div>
	</div>
</div>

<div id="hall2-bis">
	<form action=''>
		<input type="texte" value="nom"> </br>
		<input type="text" value="prénom"> </br>
		<input type="texte" value="Téléphone"> </br>
		<select id="voie2" class="form-control">
			<option>voie</option>
			<option>Francis Garnier</option>
			<option>Pérouse</option>
			<option>Bougainville</option>
			<option>Jacques Cartier</option>
			<option>Champlain</option>					
		</select>
		<textarea class="form-control" rows="3"></textarea>
		<input type="submit" value="Envoyer">
	</form>
	<%= render "layouts/webcam" %>
</div>	
</div>

<div class="menu3">
	<button type="button" class="btn btn-default">Espaces extérieurs</button>
</div>

<div class="questionnaire3">
	<button type="button" class="btn btn-default passage"> Sur une voie de passage </button> <button type="button" class="btn btn-default collectif"> Un équipement collectif </button>
</div>

<div id="collectif">
	<button type="button" class="btn btn-default poubelle"> Local à poubelles </button> <button type="button" class="btn btn-default foot"> Terrain de foot </button> 
	<button type="button" class="btn btn-default enfant"> Espace enfant </button>
</div>

<div id="poubelle">
	<form class="text-center" action=''>
		<input type="texte" value="nom"> </br>
		<input type="text" value="prénom"> </br>
		<input type="texte" value="Téléphone"> </br>
		<select id="voie3" class="form-control">
			<option>voie</option>
			<option>Francis Garnier</option>
			<option>Pérouse</option>
			<option>Bougainville</option>
			<option>Jacques Cartier</option>
			<option>Champlain</option>					
		</select>
		<textarea class="form-control" rows="3"></textarea>
		<input type="submit" value="Envoyer">
	</form>
	<%= render "layouts/webcam" %>
</div>

<div id="foot">
	<form action=''>
		<textarea class="form-control" rows="3"></textarea>
		<input type="texte" value="nom"> </br>
		<input type="text" value="prénom"> </br>
		<input type="texte" value="Téléphone"> </br>
		<input type="submit" value="Envoyer">
	</form>
	<%= render "layouts/webcam" %>
</div>

<div id="enfant">
	<form action=''>
		<textarea class="form-control" rows="3"></textarea>
		<input type="texte" value="nom"> </br>
		<input type="text" value="prénom"> </br>
		<input type="texte" value="Téléphone"> </br>
		<input type="submit" value="Envoyer">
	</form>
	<%= render "layouts/webcam" %>
</div>

<div class="passage_bis">
	<form action=''>
		<input type="texte" value="nom"> </br>
		<input type="text" value="prénom"> </br>
		<input type="texte" value="Téléphone"> </br>
		<select id="voie4" class="form-control">
			<option>voie</option>
			<option>Francis Garnier</option>
			<option>Pérouse</option>
			<option>Bougainville</option>
			<option>Jacques Cartier</option>
			<option>Champlain</option>					
		</select>
		<textarea class="form-control" rows="3"></textarea>
		<input type="submit" value="Envoyer">
	</form>
	<%= render "layouts/webcam" %>
</div>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
  var form = $('#form'); // contact form
  var submit = $('#submit');  // submit button
  var alert = $('.alert'); // alert div for show alert message

  // form submit event
  form.on('submit', function(e) {
    e.preventDefault(); // prevent default form submit

    $.ajax({
      url: '', // form action url
      type: 'POST', // form submit method get/post
      dataType: 'html', // request type html/json/xml
      data: form.serialize(), // serialize form data 
      beforeSend: function() {
      	alert.fadeOut();
        submit.html('Sending....'); // change submit button text
    },
    success: function(data) {
        alert.html(data).fadeIn(); // fade in response data
        form.trigger('reset'); // reset form
        submit.html('Send Email'); // reset submit button text
    },
    error: function(e) {
    	console.log(e)
    }
});
});
});
</script>

app/views/inquiries/show.html.erb
<h1>Photo</h1>
<p><%= image_tag @inquiry.image.url(:medium) %></p>
<p>
  <strong>Description:</strong><br />
  <%=h @inquiry.description %>
</p>
<p>
  <%= link_to "Take a new picture", new_inquiry_path %>
  | <%= link_to "See all pictures", inquiries_path %>
</p>

app/views/interieurs1/index.html.erb
<h1>Interieurs1#index</h1>
<p>Find me in app/views/interieurs1/index.html.erb</p>

app/views/interieurs2/index.html.erb
<h1>Interieurs2#index</h1>
<p>Find me in app/views/interieurs2/index.html.erb</p>

app/views/layouts/_footer.html.erb
<div class="footer">
<hr width=100%>

<h4> Powered by La Salle du Temps </h4>
</div>

app/views/layouts/_header.html.erb
<div class="page-header">
	<h1>Amicale des Beaudottes</h1>  <button id="retour" <%= link_to "Retour", root_path %> </button>
</div>

app/views/layouts/_webcam.html.erb
<div id="webcam"></div>
<script type="text/javascript">
    function onload_complete(msg) {
        // fetch the CSRF meta tag data
        var csrf_param = $('meta[name=csrf-param]').attr('content');
        var csrf_token = $('meta[name=csrf-token]').attr('content');

        // reset the api URL appending the auth token parameter
        webcam.set_api_url('<%= upload_inquiries_path %>' + '?' + csrf_param + "=" + encodeURI(encodeURI(csrf_token)));
    }

    function upload_complete(msg) {
        if (msg == 'ok') {
            $('#new_inquiry').show();
            $('#photo_description').focus();
        } else {
            alert('An error occured');
            webcam.reset();
        }
    }

    webcam.set_swf_url('/webcam.swf');
    webcam.set_api_url('<%= upload_inquiries_path %>');
    webcam.set_quality(90);
    webcam.set_shutter_sound(true, '/shutter.mp3');
    webcam.set_hook('onLoad', 'onload_complete');
    webcam.set_hook('onComplete', 'upload_complete');
    $('#webcam').html(webcam.get_html(640, 480));
</script>
<input type="button" value="Take picture" onclick="webcam.snap();"/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bdt270</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'webcam' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

</head>
<body>
<%= render "layouts/header" %>
<%= yield %>

<%= render "layouts/footer" %>
</body>
</html>